FROM jupyter/minimal-notebook:python-3.7.12

USER root
# Instalar Java
RUN apt-get update && apt-get install -y openjdk-8-jdk-headless

# Instalar PySpark + findspark
RUN pip install --no-cache-dir pyspark==2.4.5 findspark

RUN pip install --no-cache-dir pyspark==2.4.5 findspark python-dotenv


# Definir JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

USER jovyan
 